langs = [
    {"Abkhaz": "ab"},
    {"Arabic": "ar"},
    {"Assamese": "as"},
    {"Bashkir": "ba"},
    {"Basaa": "bas"},
    {"Bulgarian": "bg"},
    {"Breton": "br"},
    {"Catalan": "ca"},
    {"Hakha Chin": "cnh"},
    {"Czech": "cs"},
    {"Chuvash": "cv"},
    {"Welsh": "cy"},
    {"German": "de"},
    {"Dhivehi": "dv"},
    {"Greek": "el"},
    {"English": "en"},
    {"Esperanto": "eo"},
    {"Spanish": "es"},
    {"Estonian": "et"},
    {"Basque": "eu"},
    {"Persian": "fa"},
    {"Finnish": "fi"},
    {"French": "fr"},
    {"Frisian": "fy-NL"},
    {"Irish": "ga-IE"},
    {"Hindi": "hi"},
    {"Sorbian, Upper": "hsb"},
    {"Hungarian": "hu"},
    {"Interlingua": "ia"},
    {"Indonesian": "id"},
    {"Italian": "it"},
    {"Japanese": "ja"},
    {"Georgian": "ka"},
    {"Kabyle": "kab"},
    {"Kazakh": "kk"},
    {"Kurmanji Kurdish": "kmr"},
    {"Kyrgyz": "ky"},
    {"Luganda": "lg"},
    {"Lithuanian": "lt"},
    {"Latvian": "lv"},
    {"Mongolian": "mn"},
    {"Maltese": "mt"},
    {"Dutch": "nl"},
    {"Odia": "or"},
    {"Punjabi": "pa-IN"},
    {"Polish": "pl"},
    {"Portuguese": "pt"},
    {"Romansh Sursilvan": "rm-sursilv"},
    {"Romansh Vallader": "rm-vallader"},
    {"Romanian": "ro"},
    {"Russian": "ru"},
    {"Kinyarwanda": "rw"},
    {"Sakha": "sah"},
    {"Slovak": "sk"},
    {"Slovenian": "sl"},
    {"Swedish": "sv-SE"},
    {"Tamil": "ta"},
    {"Thai": "th"},
    {"Turkish": "tr"},
    {"Tatar": "tt"},
    {"Ukrainian": "uk"},
    {"Vietnamese": "vi"},
    {"Votic": "vot"},
    {"Chinese (China)": "zh-CN"},
    {"Chinese (Hong Kong)": "zh-HK"},
    {"Chinese (Taiwan)": "zh-TW"},
    # {"Galician": "gl"}
]
